services:
  redis:
    image: redis:7.2-alpine
    container_name: ats-redis
    ports:
      - "6379:6379"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: ats-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: atsdb
    ports:
      - "5432:5432"
    volumes:
      - ats-postgres-data:/var/lib/postgresql/data

volumes:
  ats-postgres-data:
